config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get    'weather' => 'weather_app#new'
  post   'weather' => 'weather_app#create'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  before_action :get_user,         only: [:edit, :update]
  before_action :valid_user,       only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email da duoc gui"
      redirect_to root_url
    else
      flash.now[:danger] = "Khong ton tai email nay"
      render 'new'
    end
  end

  def update
    if password_blank?
      flash.now[:danger] = "Mat khau khong duoc trong"
      render 'edit'
    elsif @user.update_attribute(user_params)
      log_in @user
      flash[:success] = "Mat khau da duoc thay doi"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private 

    def get_user
      @user = User.find_by(email: params[:email])
    end

    def valid_user
      unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def password_blank?
      params[:user][:password].blank?
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Mat khau da qua han thay doi"
        redirect_to new_password_reset_url
      end
    end

end

app/views/password_resets/edit.html.erb
<!-- set title -->
<% provide(:title, "Reset password")%>

<div class="reset-password">
  <h1>Thay doi mat khau</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user, url: password_resets_path(params[:id]) do |f| %>

        <%= render 'share/error_messages', object: f.object %>

        <%= hidden_field_tag :email, @user.email %>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label :password_confirmation, "Xac nhan mat khau" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <%= f.submit "Thay doi", class: "btn btn-primary" %>
      
      <% end %>

    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<!-- Set title -->
<% provide(:title, "Quen mat khau")%>

<div class="forgot-password">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(:password_reset, url: password_resets_path) do |f| %>
        
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.submit "Gui mail", class: "btn btn-primary btn-mail" %>
      <% end %>
    </div>
  </div>
</div>