config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get    'weather' => 'weather_app#new'
  post   'weather' => 'weather_app#create'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="footer-details"> 
      <%= link_to "Dieu khoan su dung" %> | 
      <%= link_to "Chinh sach bao mat" %> |
      <%= link_to "Gioi thieu", about_path %>
    </div>
  </div>
</div>  

app/views/layouts/_header.html.erb
<div class="header">
  <div class="menu-bar">
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("cloudservice.jpeg", alt: "Logo"), "#", class: "logo" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Trang chu", root_path %></li>
            <li><%= link_to "Gioi thieu", about_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dich vu <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Lai suat ngan hang", "#" %></li>
                <li><%= link_to "Thoi tiet", weather_path %></li>
                <li><%= link_to "BXH bai hat", "#" %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Xem thanh vien", "#" %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Vote", "#" %></li>
              </ul>
            </li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>

              <li><%= link_to "Tai khoan", edit_user_path(current_user) %></li>
              <li><%= link_to "Danh sach TV", users_path %></li>
              <li><%= link_to "Dang xuat", logout_path, method: "delete" %></li>
            <% else %>
              <li><%= link_to "Dang ki", signup_path %></li>
              <li><%= link_to "Dang nhap", login_path %></li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
  </div>
 
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type%>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>